### ISSUE TITLE
Use a version manager tool instead of get_version()

### ISSUE THREAD

**Issue by audreyr** [pydanny/cookiecutter-djangopackage#113]
Our current approach to getting the version number involves a custom `get_version()` that reads `__init__py` and parses it with a regexp: https://github.com/pydanny/cookiecutter-djangopackage/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/setup.py#L20-L29

It's better than importing the package to get the version (which causes chicken-egg problems), but really not ideal.

There are tools that can handle this for us:
- https://github.com/lgiordani/punch
- https://github.com/peritus/bumpversion

TODOs:
- Choose one of the above tools (or maybe one that I don't know about)
- Set it up with the generated package
- Remove old `get_version()` code
- Document how to increment versions with the chosen tool in `docs/versioning.rst` or wherever you think makes the most sense

**Comment by browniebroke** [comment]
[This commit](https://github.com/pydanny/cookiecutter-djangopackage/commit/ee32c20072e71d57f1cb330ca7071eba7be71a62) added bumpversion to this package, but it's currently crashing* because it cannot find the version string in the `setup.py`file, it was removed a few days ago in 89157eef71a16b9d60959141de09ce59cdf90b3c

Either we remove `[bumpversion:file:setup.py]` from `setup.cfg` or we revert 89157eef71a16b9d60959141de09ce59cdf90b3c and document it properly.

(*) I just tried to run bumpversion on a recently generated package and I had: `AssertionError: Did not find '0.1.0' or '0.1.0' in file setup.py`.

**Comment by audiolion** [comment]
I just ran into this and thought I did something wrong with the setup, I feel like it should be reverted until fixed because grabbing the latest from github includes this bug :(
